#!/usr/bin/env python3
"""Fixtures for testing"""

org_payload = {
    "login": "google",
    "id": 1342004,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
    "url": "https://api.github.com/orgs/google",
    "repos_url": "https://api.github.com/orgs/google/repos",
    "events_url": "https://api.github.com/orgs/google/events",
    "hooks_url": "https://api.github.com/orgs/google/hooks",
    "issues_url": "https://api.github.com/orgs/google/issues",
    "members_url": "https://api.github.com/orgs/google/members{/member}",
    "public_members_url": "https://api.github.com/orgs/google/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
    "description": "Google ❤️ Open Source",
    "name": "Google",
    "company": None,
    "blog": "https://opensource.google.com/",
    "location": None,
    "email": None,
    "twitter_username": None,
    "is_verified": True,
    "has_organization_projects": True,
    "has_repository_projects": True,
    "public_repos": 2607,
    "public_gists": 0,
    "followers": 0,
    "following": 0,
    "html_url": "https://github.com/google",
    "created_at": "2012-01-18T01:30:18Z",
    "updated_at": "2019-11-25T22:46:43Z",
    "type": "Organization"
}

repos_payload = [
    {
        "id": 7697149,
        "node_id": "MDEwOlJlcG9zaXRvcnk3Njk3MTQ5",
        "name": "episodes.dart",
        "full_name": "google/episodes.dart",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "followers_url": "https://api.github.com/users/google/followers",
            "following_url": "https://api.github.com/users/google/following{/other_user}",
            "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/google/subscriptions",
            "organizations_url": "https://api.github.com/users/google/orgs",
            "repos_url": "https://api.github.com/users/google/repos",
            "events_url": "https://api.github.com/users/google/events{/privacy}",
            "received_events_url": "https://api.github.com/users/google/received_events",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/episodes.dart",
        "description": "A framework for timing performance of web apps.",
        "fork": False,
        "url": "https://api.github.com/repos/google/episodes.dart",
        "archive_url": "https://api.github.com/repos/google/episodes.dart/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/google/episodes.dart/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/google/episodes.dart/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/google/episodes.dart/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/google/episodes.dart/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/google/episodes.dart/comments{/number}",
        "commits_url": "https://api.github.com/repos/google/episodes.dart/commits{/sha}",
        "compare_url": "https://api.github.com/repos/google/episodes.dart/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/google/episodes.dart/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/google/episodes.dart/contributors",
        "deployments_url": "https://api.github.com/repos/google/episodes.dart/deployments",
        "downloads_url": "https://api.github.com/repos/google/episodes.dart/downloads",
        "events_url": "https://api.github.com/repos/google/episodes.dart/events",
        "forks_url": "https://api.github.com/repos/google/episodes.dart/forks",
        "git_commits_url": "https://api.github.com/repos/google/episodes.dart/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/episodes.dart/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/episodes.dart/git/tags{/sha}",
        "git_url": "git://github.com/google/episodes.dart.git",
        "issue_comment_url": "https://api.github.com/repos/google/episodes.dart/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/google/episodes.dart/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/google/episodes.dart/issues{/number}",
        "keys_url": "https://api.github.com/repos/google/episodes.dart/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/google/episodes.dart/labels{/name}",
        "languages_url": "https://api.github.com/repos/google/episodes.dart/languages",
        "merges_url": "https://api.github.com/repos/google/episodes.dart/merges",
        "milestones_url": "https://api.github.com/repos/google/episodes.dart/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/episodes.dart/notifications{?since,all,participating}",
        "pulls_url": "https://api.github.com/repos/google/episodes.dart/pulls{/number}",
        "releases_url": "https://api.github.com/repos/google/episodes.dart/releases{/id}",
        "ssh_url": "git@github.com:google/episodes.dart.git",
        "stargazers_url": "https://api.github.com/repos/google/episodes.dart/stargazers",
        "statuses_url": "https://api.github.com/repos/google/episodes.dart/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/google/episodes.dart/subscribers",
        "subscription_url": "https://api.github.com/repos/google/episodes.dart/subscription",
        "tags_url": "https://api.github.com/repos/google/episodes.dart/tags",
        "teams_url": "https://api.github.com/repos/google/episodes.dart/teams",
        "trees_url": "https://api.github.com/repos/google/episodes.dart/git/trees{/sha}",
        "clone_url": "https://github.com/google/episodes.dart.git",
        "mirror_url": None,
        "hooks_url": "https://api.github.com/repos/google/episodes.dart/hooks",
        "svn_url": "https://github.com/google/episodes.dart",
        "homepage": "",
        "language": "Dart",
        "forks_count": 22,
        "stargazers_count": 12,
        "watchers_count": 12,
        "size": 351,
        "default_branch": "master",
        "open_issues_count": 0,
        "is_template": False,
        "topics": [],
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "has_downloads": True,
        "archived": False,
        "disabled": False,
        "visibility": "public",
        "pushed_at": "2019-09-23T11:53:58Z",
        "created_at": "2013-01-19T00:31:37Z",
        "updated_at": "2019-09-23T11:53:58Z",
        "permissions": {
            "admin": False,
            "push": False,
            "pull": True
        },
        "template_repository": None,
        "temp_clone_token": "",
        "delete_branch_on_merge": False,
        "subscribers_count": 15,
        "network_count": 22,
        "license": {
            "key": "bsd-3-clause",
            "name": "BSD 3-Clause \"New\" or \"Revised\" License",
            "spdx_id": "BSD-3-Clause",
            "url": "https://api.github.com/licenses/bsd-3-clause",
            "node_id": "MDc6TGljZW5zZW5vZGVfaWQ6MQ=="
        }
    },
    {
        "id": 8566972,
        "node_id": "MDEwOlJlcG9zaXRvcnk4NTY2OTcy",
        "name": "kratu",
        "full_name": "google/kratu",
        "private": False,
        "owner": {
            "login": "google",
            "id": 1342004,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzNDIwMDQ=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/1342004?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/google",
            "html_url": "https://github.com/google",
            "followers_url": "https://api.github.com/users/google/followers",
            "following_url": "https://api.github.com/users/google/following{/other_user}",
            "gists_url": "https://api.github.com/users/google/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/google/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/google/subscriptions",
            "organizations_url": "https://api.github.com/users/google/orgs",
            "repos_url": "https://api.github.com/users/google/repos",
            "events_url": "https://api.github.com/users/google/events{/privacy}",
            "received_events_url": "https://api.github.com/users/google/received_events",
            "type": "Organization",
            "site_admin": False
        },
        "html_url": "https://github.com/google/kratu",
        "description": "An open-source JavaScript library that allows for easy formatting and displaying of tabular data",
        "fork": False,
        "url": "https://api.github.com/repos/google/kratu",
        "archive_url": "https://api.github.com/repos/google/kratu/{archive_format}{/ref}",
        "assignees_url": "https://api.github.com/repos/google/kratu/assignees{/user}",
        "blobs_url": "https://api.github.com/repos/google/kratu/git/blobs{/sha}",
        "branches_url": "https://api.github.com/repos/google/kratu/branches{/branch}",
        "collaborators_url": "https://api.github.com/repos/google/kratu/collaborators{/collaborator}",
        "comments_url": "https://api.github.com/repos/google/kratu/comments{/number}",
        "commits_url": "https://api.github.com/repos/google/kratu/commits{/sha}",
        "compare_url": "https://api.github.com/repos/google/kratu/compare/{base}...{head}",
        "contents_url": "https://api.github.com/repos/google/kratu/contents/{+path}",
        "contributors_url": "https://api.github.com/repos/google/kratu/contributors",
        "deployments_url": "https://api.github.com/repos/google/kratu/deployments",
        "downloads_url": "https://api.github.com/repos/google/kratu/downloads",
        "events_url": "https://api.github.com/repos/google/kratu/events",
        "forks_url": "https://api.github.com/repos/google/kratu/forks",
        "git_commits_url": "https://api.github.com/repos/google/kratu/git/commits{/sha}",
        "git_refs_url": "https://api.github.com/repos/google/kratu/git/refs{/sha}",
        "git_tags_url": "https://api.github.com/repos/google/kratu/git/tags{/sha}",
        "git_url": "git://github.com/google/kratu.git",
        "issue_comment_url": "https://api.github.com/repos/google/kratu/issues/comments{/number}",
        "issue_events_url": "https://api.github.com/repos/google/kratu/issues/events{/number}",
        "issues_url": "https://api.github.com/repos/google/kratu/issues{/number}",
        "keys_url": "https://api.github.com/repos/google/kratu/keys{/key_id}",
        "labels_url": "https://api.github.com/repos/google/kratu/labels{/name}",
        "languages_url": "https://api.github.com/repos/google/kratu/languages",
        "merges_url": "https://api.github.com/repos/google/kratu/merges",
        "milestones_url": "https://api.github.com/repos/google/kratu/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/google/kratu/notifications{?since,all,participating}",
        "pulls_url": "https://api.github.com/repos/google/kratu/pulls{/number}",
        "releases_url": "https://api.github.com/repos/google/kratu/releases{/id}",
        "ssh_url": "git@github.com:google/kratu.git",
        "stargazers_url": "https://api.github.com/repos/google/kratu/stargazers",
        "statuses_url": "https://api.github.com/repos/google/kratu/statuses/{sha}",
        "subscribers_url": "https://api.github.com/repos/google/kratu/subscribers",
        "subscription_url": "https://api.github.com/repos/google/kratu/subscription",
        "tags_url": "https://api.github.com/repos/google/kratu/tags",
        "teams_url": "https://api.github.com/repos/google/kratu/teams",
        "trees_url": "https://api.github.com/repos/google/kratu/git/trees{/sha}",
        "clone_url": "https://github.com/google/kratu.git",
        "mirror_url": None,
        "hooks_url": "https://api.github.com/repos/google/kratu/hooks",
        "svn_url": "https://github.com/google/kratu",
        "homepage": "",
        "language": "JavaScript",
        "forks_count": 32,
        "stargazers_count": 179,
        "watchers_count": 179,
        "size": 5019,
        "default_branch": "master",
        "open_issues_count": 3,
        "is_template": False,
        "topics": [],
        "has_issues": True,
        "has_projects": True,
        "has_wiki": True,
        "has_pages": False,
        "has_downloads": True,
        "archived": False,
        "disabled": False,
        "visibility": "public",
        "pushed_at": "2018-06-06T12:26:53Z",
        "created_at": "2013-03-04T22:52:33Z",
        "updated_at": "2019-11-15T22:22:16Z",
        "permissions": {
            "admin": False,
            "push": False,
            "pull": True
        },
        "template_repository": None,
        "temp_clone_token": "",
        "delete_branch_on_merge": False,
        "subscribers_count": 15,
        "network_count": 32,
        "license": {
            "key": "apache-2.0",
            "name": "Apache License 2.0",
            "spdx_id": "Apache-2.0",
            "url": "https://api.github.com/licenses/apache-2.0",
            "node_id": "MDc6TGljZW5zZW5vZGVfaWQ6Mg=="
        }
    }
]

expected_repos = ["episodes.dart", "kratu"]

apache2_repos = ["kratu"]
